package googlemod

import (
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"io/ioutil"
	"net/http"
	"regexp"
	"strings"
)

func scrape(query string) (links []string) {

	req, err := http.NewRequest("GET", "https://www.google.com/search?tbm=isch&gs_l=img&safe=yes&q="+query, nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	req.Header.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36")

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Println(err)
		return
	}

	defer res.Body.Close()

	doc, err := goquery.NewDocumentFromReader(res.Body)
	if err != nil {
		fmt.Println(err)
		return
	}

	links = []string{}

	doc.Find("img.Q4LuWd").Each(func(i int, s *goquery.Selection) {
		if link, ok := s.Attr("data-src"); ok {
			links = append(links, link)
		}
	})
	return
}

type AutoGenerated struct {
	Ou string `json:"data-src"`
}

//var reg = regexp.MustCompile("\"((http)?s?://.*\\.(?:png|jpg|gif))\"")
//var reg = regexp.MustCompile(`"((http)s?://.*\.(?:png|jpg|gif))"`)

var reg = regexp.MustCompile(`"(http)s?://([^"])*\.(gif|png|jpg)"`)

func Scrape(query string) (links []string) {

	req, err := http.NewRequest("GET", "https://www.google.com/search?tbm=isch&gs_l=img&safe=yes&q="+query, nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	req.Header.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36")

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer res.Body.Close()

	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		return
	}

	matches := reg.FindAll(body, -1)

	for _, m := range matches {
		ma := string(m)
		ma = strings.TrimPrefix(ma, `"`)
		ma = strings.TrimSuffix(ma, `"`)
		fmt.Println(ma)
		links = append(links, ma)
	}
	return
}
